### ISSUE TITLE
No push access

### ISSUE THREAD

**Issue by rolandknapp** [Jake-Eisaguirre/OpenScience_NSFPresentation#1]
@Jake-Eisaguirre I tried to push my edits and received authentication errors. Do I have push access to this repo? It could also be an issue on my end. I am working from my laptop, and I don't have much experience working with Git/GitHub from that device (since most of my work is done on my office desktop computer). The specific error message is: 

> remote: Invalid username or password.
> fatal: Authentication failed for 'https://github.com/Jake-Eisaguirre/OpenScience_NSFPresentation.git/'

**Comment by Jake-Eisaguirre** [comment]
You should have full collaborator access to the repo. That error makes me think you need to re-authenticate your laptop to your github account. 

Try below
```
# Check Github Info
usethis::git_sitrep()

# If github token has expired for your laptop
usethis::create_github_token()
# then
gitcreds::gitcreds_set()
```

**Comment by rolandknapp** [comment]
Thanks for the tip. This seems to have resolved the issue.
